In [1]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

pd.set_option("display.max_columns", None)

In [3]:
yearly_df = pd.read_csv(r"D:\spotify\data\processed\analytics_ready\yearly_trends.csv")

In [4]:
yearly_df.head()

,year,popularity,danceability,energy,valence,tempo,loudness,speechiness,acousticness,instrumentalness,liveness
0,2009,37.000000,0.643375,0.728625,0.608375,137.585500,-5.568875,0.045988,0.127415,0.004233,0.218687
1,2010,31.300000,0.690700,0.798300,0.690100,113.056800,-6.411200,0.134150,0.088664,0.000009,0.212060
2,2011,29.714286,0.681857,0.745286,0.638000,127.295000,-6.728571,0.129357,0.107857,0.136143,0.165343
3,2012,27.666667,0.627778,0.805667,0.609556,135.262444,-5.521333,0.091244,0.043376,0.000009,0.116178
4,2013,25.769231,0.618846,0.642385,0.519385,114.736154,-6.422000,0.039531,0.088300,0.007824,0.267046

In [5]:
features = ["danceability", "energy", "valence"]

fig = px.line(
    yearly_df,
    x="year",
    y=features,
    markers=True,
    title="Evolution of Key Spotify Audio Features Over Time"
)

fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Feature Value",
    legend_title="Audio Feature",
    template="plotly_dark"
)

fig.show()

In [6]:
fig = px.area(
    yearly_df,
    x="year",
    y=features,
    title="Stacked View of Audio Feature Trends",
)

fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Feature Intensity",
    template="plotly_dark"
)

fig.show()

In [7]:
fig = px.line(
    yearly_df,
    x="year",
    y="danceability",
    markers=True,
    title="Danceability Trend with Pandemic Period Highlight"
)

fig.add_vrect(
    x0=2020, x1=2021,
    fillcolor="red",
    opacity=0.15,
    annotation_text="Pandemic Era",
    annotation_position="top left"
)

fig.update_layout(template="plotly_dark")
fig.show()

In [8]:
genre_df = pd.read_csv(r"D:\spotify\data\processed\analytics_ready\genre_audio_analysis.csv")

In [9]:
genre_df.head()

,track_id_x,track_name_x,track_number,track_popularity,explicit,artist_name_x,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min,merge_key,artist_name_y,track_id_y,track_name_y,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,popularity,track_genre
0,68HyvTUsmlpH1UJo9tn5v3,Zombie,66,0,False,The Cranberries,76,5401129,NaN,4UkEvuAF0oirvH9HUAWSnk,The Best 90s Album In The World...Ever!,2021-05-25,77,compilation,5.12,zombie_the cranberries,The Cranberries,6XKv6ZUpghrz96imZfpOX3,Zombie,0.0139,0.309,308293,0.640,0.00343,7,0.3670,-8.915,1,0.0340,166.969,4,0.274,20,rock
1,4nyY8oVjbX2d4qzlpiVM5n,Ruin My Life,9,74,True,Zara Larsson,77,10912927,NaN,79y7DSLFQH3907u4ysOMGr,Poster Girl,2021-03-05,12,album,3.16,ruin my life_zara larsson,Zara Larsson,5tAa8Uaqr4VvA3693mbIhU,Ruin My Life,0.4230,0.665,190932,0.699,0.00000,11,0.0969,-5.265,1,0.0578,124.896,4,0.585,86,electro
2,4nyY8oVjbX2d4qzlpiVM5n,Ruin My Life,9,74,True,Zara Larsson,77,10912927,NaN,79y7DSLFQH3907u4ysOMGr,Poster Girl,2021-03-05,12,album,3.16,ruin my life_zara larsson,Zara Larsson,5tAa8Uaqr4VvA3693mbIhU,Ruin My Life,0.4230,0.665,190932,0.699,0.00000,11,0.0969,-5.265,1,0.0578,124.896,4,0.585,86,house
3,11FvynPeozvRw769iN9kV7,Call Out My Name,11,46,False,The Weeknd,93,112957721,"r&b pop, alternative r&b, hip hop, synthpop",5L5evi5tJPh8WaEFAQp7Tp,The Highlights,2021-02-05,18,compilation,3.80,call out my name_the weeknd,The Weeknd,4MPTj8lMMvxLwT3EwuXFop,Call Out My Name,0.2110,0.449,228373,0.599,0.00000,1,0.3270,-4.892,1,0.0369,134.144,3,0.165,82,pop
4,7t3Xdbufg7q2onVsR8RBdY,Fire On Fire,5,78,False,Sam Smith,81,26275803,soft pop,5XCBX16KNYsAe7V5hQV9mC,Love Goes,2020-10-30,17,album,4.11,fire on fire_sam smith,Sam Smith,5rFj8OzffT0iggSjcBaeND,Fire On Fire,0.5130,0.598,246735,0.419,0.00000,1,0.1700,-7.383,0,0.0473,114.938,4,0.330,85,dance

In [10]:
genre_counts = (
    genre_df["track_genre"]
    .value_counts()
    .reset_index()
)

genre_counts.columns = ["track_genre", "count"]

fig = px.bar(
    genre_counts,
    x="track_genre",
    y="count",
    title="Distribution of Tracks Across Genres",
    color="count",
    template="plotly_dark"
)

fig.update_layout(
    xaxis_title="Genre",
    yaxis_title="Number of Tracks"
)

fig.show()

In [11]:
feature = "energy"  # later becomes dropdown in Streamlit

genre_avg = (
    genre_df
    .groupby("track_genre")[feature]
    .mean()
    .reset_index()
    .sort_values(by=feature, ascending=False)
)

fig = px.bar(
    genre_avg,
    x=feature,
    y="track_genre",
    orientation="h",
    title=f"Average {feature.capitalize()} by Genre",
    color=feature,
    template="plotly_dark"
)

fig.show()

In [12]:
top_n = 10

top_genres = genre_counts.head(top_n)

fig = px.pie(
    top_genres,
    names="track_genre",
    values="count",
    title="Top Genres by Dataset Share",
    hole=0.4
)

fig.update_traces(textposition="inside", textinfo="percent+label")
fig.update_layout(template="plotly_dark")

fig.show()

In [13]:
fig = px.box(
    genre_df,
    x="track_genre",
    y=feature,
    title=f"{feature.capitalize()} Distribution Across Genres",
    template="plotly_dark"
)

fig.show()

In [14]:
chart_df = pd.read_csv(r"D:\spotify\data\processed\analytics_ready\chart_vs_nonchart.csv")

In [15]:
chart_df.head()

,track_id_x,track_name_x,track_number,track_popularity,explicit,artist_name_x,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min,merge_key,artist_name_y,track_id_y,track_name_y,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,popularity,track_genre,is_chart_song
0,5oJmBs9L5xwDkUbDWqn6Wr,This City,4,61,False,Sam Fischer,55,341193,NaN,2FGOxwdP7MMd4GfVl2Uf7f,"I Love You, Please Don't Hate Me",2023-11-30,15,album,3.26,this city_sam fischer,Sam Fischer,7kF3x1XJXGcgQWFemulw4q,This City,0.7310,0.602,194853,0.377,0.00000,11,0.0808,-6.213,1,0.0446,73.877,4,0.518,54,NaN,True
1,68HyvTUsmlpH1UJo9tn5v3,Zombie,66,0,False,The Cranberries,76,5401129,NaN,4UkEvuAF0oirvH9HUAWSnk,The Best 90s Album In The World...Ever!,2021-05-25,77,compilation,5.12,zombie_the cranberries,The Cranberries,6XKv6ZUpghrz96imZfpOX3,Zombie,0.0139,0.309,308293,0.640,0.00343,7,0.3670,-8.915,1,0.0340,166.969,4,0.274,20,rock,True
2,4nyY8oVjbX2d4qzlpiVM5n,Ruin My Life,9,74,True,Zara Larsson,77,10912927,NaN,79y7DSLFQH3907u4ysOMGr,Poster Girl,2021-03-05,12,album,3.16,ruin my life_zara larsson,Zara Larsson,5tAa8Uaqr4VvA3693mbIhU,Ruin My Life,0.4230,0.665,190932,0.699,0.00000,11,0.0969,-5.265,1,0.0578,124.896,4,0.585,86,edm,True
3,4nyY8oVjbX2d4qzlpiVM5n,Ruin My Life,9,74,True,Zara Larsson,77,10912927,NaN,79y7DSLFQH3907u4ysOMGr,Poster Girl,2021-03-05,12,album,3.16,ruin my life_zara larsson,Zara Larsson,5tAa8Uaqr4VvA3693mbIhU,Ruin My Life,0.4230,0.665,190932,0.699,0.00000,11,0.0969,-5.265,1,0.0578,124.896,4,0.585,86,electro,True
4,4nyY8oVjbX2d4qzlpiVM5n,Ruin My Life,9,74,True,Zara Larsson,77,10912927,NaN,79y7DSLFQH3907u4ysOMGr,Poster Girl,2021-03-05,12,album,3.16,ruin my life_zara larsson,Zara Larsson,5tAa8Uaqr4VvA3693mbIhU,Ruin My Life,0.4230,0.665,190932,0.699,0.00000,11,0.0969,-5.265,1,0.0578,124.896,4,0.585,86,house,True

In [28]:
feature = "energy"  # will become dropdown later

mean_df = (
    chart_df
    .groupby("is_chart_song")[feature]
    .mean()
    .reset_index()
)

mean_df["is_chart_song"] = mean_df["is_chart_song"].map(
    {True: "Chart", False: "Non-Chart"}
)

fig = px.bar(
    mean_df,
    x="is_chart_song",
    y=feature,
    color="is_chart_song",
    title=f"Average {feature.capitalize()} — Chart vs Non-Chart Songs",
    template="plotly_dark",
    text_auto=".2f"
)

fig.show()

In [17]:
features = [
    "danceability",
    "energy",
    "valence",
    "loudness",
    "tempo"
]

mean_features = (
    chart_df
    .groupby("is_chart_song")[features]
    .mean()
    .T
    .reset_index()
)

mean_features.columns = ["feature", "non_chart", "chart"]

mean_features["difference"] = mean_features["chart"] - mean_features["non_chart"]
mean_features = mean_features.sort_values("difference", ascending=False)

fig = px.bar(
    mean_features,
    x="difference",
    y="feature",
    orientation="h",
    title="Feature Differences: Chart vs Non-Chart Songs",
    template="plotly_dark",
    text_auto=".3f"
)

fig.show()

In [18]:
fig = px.scatter(
    mean_features,
    x="difference",
    y="feature",
    size=mean_features["difference"].abs(),
    color="difference",
    title="Impact of Audio Features on Chart Presence",
    template="plotly_dark"
)

fig.show()

In [19]:
fig = px.box(
    chart_df,
    x="is_chart_song",
    y=feature,
    title=f"{feature.capitalize()} Distribution: Chart vs Non-Chart",
    template="plotly_dark"
)

fig.show()

In [20]:
pca_df = pd.read_csv(r"D:\spotify\data\processed\analytics_ready\audio_feature_pca.csv")

In [21]:
pca_df.head()

        PC1       PC2  popularity
0 -1.528784  0.430293          54
1 -0.320407 -2.223293          20
2  0.461922 -0.025708          86
3 -0.406854 -0.279047          21
4 -0.280251 -1.681483          82

In [22]:
threshold = 70  # later becomes a slider in Streamlit

filtered_df = pca_df[pca_df["popularity"] >= threshold]

fig = px.scatter(
    filtered_df,
    x="PC1",
    y="PC2",
    color="popularity",
    title=f"PCA of Audio Features (Popularity ≥ {threshold})",
    color_continuous_scale="viridis",
    template="plotly_dark"
)

fig.show()

In [23]:
fig = px.density_contour(
    pca_df,
    x="PC1",
    y="PC2",
    title="Density of Songs in Audio Feature Space",
    template="plotly_dark"
)

fig.show()

In [24]:
fig = px.scatter(
    pca_df,
    x="PC1",
    y="PC2",
    color="popularity",
    opacity=0.4,
    title="PCA with Density Perspective",
    color_continuous_scale="viridis",
    template="plotly_dark"
)

fig.show()

In [25]:
pop_cutoff = pca_df["popularity"].quantile(0.90)

top_hits = pca_df[pca_df["popularity"] >= pop_cutoff]

fig = px.scatter(
    pca_df,
    x="PC1",
    y="PC2",
    opacity=0.2,
    color_discrete_sequence=["gray"],
    title="Top 10% Popular Songs Highlighted",
    template="plotly_dark"
)

fig.add_scatter(
    x=top_hits["PC1"],
    y=top_hits["PC2"],
    mode="markers",
    marker=dict(color="red", size=6),
    name="Top 10% Popular Songs"
)

fig.show()

In [26]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=4, random_state=42)
pca_df["cluster"] = kmeans.fit_predict(pca_df[["PC1", "PC2"]])

fig = px.scatter(
    pca_df,
    x="PC1",
    y="PC2",
    color="cluster",
    title="KMeans Clusters in Audio Feature Space",
    template="plotly_dark"
)

fig.show()